NAME		:= sample_project
DEBUG		:= -g -fsanitize=address -fsanitize=undefined
CC			:= gcc
CFLAGS		:= -Wall -Werror -Wextra
INC			:= inc
SRC			:= 
OBJ			:= 

all: $(SUBMODULES) $(NAME)

debug:

$(SUBMODULES):
	@git submodule init
	@git submodule update

	

clean:

fclean:

re: